name: flutter_tranviendai
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  dio: ^5.2.1+1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  http: ^0.13.5
  pretty_dio_logger: ^1.3.1
  shared_preferences: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/check.png
    - assets/images/minus.png
    - assets/images/nike.png
    - assets/images/plus.png
    - assets/images/trash.png
  fonts:
    - family: rubik
      fonts:
        - asset: assets/fonts/rubik.ttf
        - asset: assets/fonts/rubikB.ttf